"""Tests for :mod:`quoss.orbits.geometry`.

V1 (invariants) plus V3 (astropy AltAz, frozen reference data) — see
``tests/golden/README.md`` for what each level proves. The V3 case data is
generated by ``tests/golden/generators/gen_geometry_reference.py`` into
``tests/golden/data/geometry_reference.json``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import pytest

from quoss.core.constants import (
    EGM96_MU_KM3_S2,
    SPEED_OF_LIGHT_M_S,
    WGS84_RADIUS_EQUATORIAL_KM,
)
from quoss.core.errors import DomainError
from quoss.core.types import TimeGrid
from quoss.orbits.frames import Frame, geodetic_to_itrf, gmst_rad, itrf_to_teme_state
from quoss.orbits.geometry import (
    LookAngles,
    doppler_rate_hz_s,
    doppler_shift_hz,
    look_angles,
)
from quoss.orbits.kepler import ClassicalElements
from quoss.orbits.propagator import PropagationMethod, Trajectory, propagate

CASTELLDEFELS_LAT_RAD = np.deg2rad(41.2750)
CASTELLDEFELS_LON_RAD = np.deg2rad(1.9875)
CASTELLDEFELS_ALT_KM = 0.030

REFERENCE_PATH = Path(__file__).resolve().parents[1] / "golden" / "data" / "geometry_reference.json"


def _sso_700km(*, raan_rad: float, true_anomaly_rad: float) -> ClassicalElements:
    """Build a 700 km sun-synchronous orbit, the same numbers used throughout this repo.

    Same values as the worked example in ``perturbations.py``'s
    ``secular_rates_j2`` docstring, so a reader who has seen that example
    already knows this orbit.
    """
    return ClassicalElements.from_semi_major_axis(
        semi_major_axis_km=7078.137,
        eccentricity=0.001,
        inclination_rad=np.deg2rad(98.19),
        raan_rad=raan_rad,
        argp_rad=0.0,
        true_anomaly_rad=true_anomaly_rad,
    )


def _propagate_orbit(coe: ClassicalElements, *, span_s: float, n_samples: int) -> Trajectory:
    """Propagate over at most one period, in ``n_samples`` evenly spaced steps.

    Takes a sample *count* rather than a step size on purpose: capping the
    span at one period means the actual duration is whatever fraction of
    ``span_s`` the orbit allows, and :meth:`TimeGrid.uniform` rejects a
    ``step_s`` that does not divide that duration exactly. A sample count has
    no such constraint.
    """
    period_s = 2.0 * np.pi * np.sqrt(coe.semi_major_axis_km[0] ** 3 / EGM96_MU_KM3_S2)
    duration_s = min(span_s, period_s)
    grid = TimeGrid.uniform(epoch_jd=2460676.5, duration_s=duration_s, n=n_samples)
    return propagate(coe, grid, method=PropagationMethod.TWO_BODY)


def _up_unit_vector(latitude_rad: float, longitude_rad: float) -> np.ndarray:
    """Return the WGS-84 geodetic normal at a latitude/longitude, as a unit vector.

    The exact "up" direction :func:`~quoss.orbits.frames.enu_from_itrf` builds
    its basis from. Deliberately **not** ``geodetic_to_itrf(lat, lon, 0)``
    normalised: that point sits *on the ellipsoid*, and except at the poles or
    the equator its direction from the origin is not this normal — the same
    distinction ``docs/adr`` material on WGS-84 discusses for geodetic versus
    geocentric latitude. Adding a distance along the wrong one of the two
    would not land exactly at the zenith a test wants to construct.
    """
    return np.array(
        [
            np.cos(latitude_rad) * np.cos(longitude_rad),
            np.cos(latitude_rad) * np.sin(longitude_rad),
            np.sin(latitude_rad),
        ]
    )


def _trajectory_from_itrf_state(
    r_itrf_km: np.ndarray, v_itrf_km_s: np.ndarray, epoch_jd: float
) -> Trajectory:
    """Build a two-sample TEME Trajectory from one state stated in ITRF.

    The tests below want to reason about "the satellite is due east of the
    station" or "moving purely north" — statements about the *rotating*
    Earth-fixed frame. Building the state directly in ITRF and rotating it
    into TEME with :func:`~quoss.orbits.frames.itrf_to_teme_state` (the exact
    inverse of the rotation ``look_angles`` applies internally) keeps that
    geometry exact, rather than re-deriving the rotation by hand in every
    test. Two samples, not one, only because :class:`TimeGrid` requires at
    least two; every caller reads index 0 and ignores index 1.
    """
    epochs = np.array([epoch_jd, epoch_jd + 1.0 / 86_400.0])
    theta = gmst_rad(epochs)
    r_itrf = np.tile(r_itrf_km, (2, 1))
    v_itrf = np.tile(v_itrf_km_s, (2, 1))
    r_teme, v_teme = itrf_to_teme_state(r_itrf, v_itrf, theta)
    grid = TimeGrid.uniform(epoch_jd=epoch_jd, duration_s=1.0, n=2)
    return Trajectory(
        r_km=r_teme[np.newaxis, :, :],
        v_km_s=v_teme[np.newaxis, :, :],
        grid=grid,
        frame=Frame.TEME,
        method=PropagationMethod.TWO_BODY,
    )


# --------------------------------------------------------------------------- #
# V1 — geometry invariants
# --------------------------------------------------------------------------- #
class TestZenithIsElevationNinety:
    """A satellite placed exactly on the station's zenith normal reads elevation 90.

    Built directly in ITRF via :func:`_up_unit_vector`, not from an orbit: the
    satellite is put at the station's own position plus 700 km along the exact
    normal :func:`~quoss.orbits.frames.enu_from_itrf` uses as "up", so
    elevation 90 deg and range 700 km both hold to floating-point precision,
    not just approximately.
    """

    @pytest.mark.physics
    def test_zenith(self) -> None:
        up = _up_unit_vector(CASTELLDEFELS_LAT_RAD, CASTELLDEFELS_LON_RAD)
        station_r = geodetic_to_itrf(
            CASTELLDEFELS_LAT_RAD, CASTELLDEFELS_LON_RAD, CASTELLDEFELS_ALT_KM
        )[0]
        r_itrf = station_r + up * 700.0
        traj = _trajectory_from_itrf_state(r_itrf, np.zeros(3), epoch_jd=2460676.5)
        angles = look_angles(
            traj, CASTELLDEFELS_LAT_RAD, CASTELLDEFELS_LON_RAD, CASTELLDEFELS_ALT_KM
        )
        assert angles.elevation_rad[0, 0] == pytest.approx(np.pi / 2, abs=1e-9)
        assert angles.range_km[0, 0] == pytest.approx(700.0, abs=1e-9)


class TestAntipodeIsBelowHorizon:
    """A satellite in the "down" direction from the station is not visible.

    Placed along ``-up`` rather than at the geometric antipode of the Earth:
    what this checks is that a negative elevation is possible and correctly
    signed, not any particular pass geometry.
    """

    @pytest.mark.physics
    def test_antipode(self) -> None:
        up = _up_unit_vector(CASTELLDEFELS_LAT_RAD, CASTELLDEFELS_LON_RAD)
        station_r = geodetic_to_itrf(
            CASTELLDEFELS_LAT_RAD, CASTELLDEFELS_LON_RAD, CASTELLDEFELS_ALT_KM
        )[0]
        r_itrf = station_r - up * 700.0
        traj = _trajectory_from_itrf_state(r_itrf, np.zeros(3), epoch_jd=2460676.5)
        angles = look_angles(
            traj, CASTELLDEFELS_LAT_RAD, CASTELLDEFELS_LON_RAD, CASTELLDEFELS_ALT_KM
        )
        assert angles.elevation_rad[0, 0] == pytest.approx(-np.pi / 2, abs=1e-9)


class TestAzimuthWraps:
    """Azimuth is always in [0, 2 pi), including for satellites due north or south."""

    @pytest.mark.physics
    @pytest.mark.parametrize("raan_offset_deg", [0.0, 45.0, 90.0, 135.0, 180.0, 270.0, 359.0])
    def test_wraps(self, raan_offset_deg: float) -> None:
        coe = _sso_700km(
            raan_rad=CASTELLDEFELS_LON_RAD + np.deg2rad(raan_offset_deg),
            true_anomaly_rad=0.0,
        )
        traj = _propagate_orbit(coe, span_s=6000.0, n_samples=200)
        angles = look_angles(
            traj, CASTELLDEFELS_LAT_RAD, CASTELLDEFELS_LON_RAD, CASTELLDEFELS_ALT_KM
        )
        assert np.all(angles.azimuth_rad >= 0.0)
        assert np.all(angles.azimuth_rad < 2.0 * np.pi)


class TestRangeEqualsVectorNorm:
    """range_km is exactly the norm the ENU components (elevation/azimuth/range) imply.

    ``range * (cos(el) sin(az), cos(el) cos(az), sin(el))`` reconstructs the
    ENU vector this module computed internally; if ``range_km`` disagreed with
    that vector's own norm, the reconstruction would not close — a stronger
    check than trusting ``range_km`` in isolation.
    """

    @pytest.mark.physics
    def test_reconstruction(self) -> None:
        coe = _sso_700km(raan_rad=np.deg2rad(15.0), true_anomaly_rad=np.deg2rad(200.0))
        traj = _propagate_orbit(coe, span_s=3000.0, n_samples=70)
        angles = look_angles(
            traj, CASTELLDEFELS_LAT_RAD, CASTELLDEFELS_LON_RAD, CASTELLDEFELS_ALT_KM
        )
        east = angles.range_km * np.cos(angles.elevation_rad) * np.sin(angles.azimuth_rad)
        north = angles.range_km * np.cos(angles.elevation_rad) * np.cos(angles.azimuth_rad)
        up = angles.range_km * np.sin(angles.elevation_rad)
        reconstructed_range = np.sqrt(east**2 + north**2 + up**2)
        np.testing.assert_allclose(reconstructed_range, angles.range_km, rtol=1e-12)


class TestRangeRateMatchesFiniteDifference:
    """range_rate_km_s agrees with a central finite difference of range_km itself.

    This does not validate the *physics* (both sides come from this module's
    own rotation of the same trajectory) — it validates that the analytic
    range-rate formula (projecting relative velocity onto the line of sight)
    really is the derivative of the range this module also reports, catching a
    sign error or a dropped term that a shape or wrap-range check would not.
    """

    @pytest.mark.physics
    def test_matches_derivative(self) -> None:
        coe = _sso_700km(raan_rad=np.deg2rad(15.0), true_anomaly_rad=np.deg2rad(200.0))
        step_s = 0.05
        grid = TimeGrid.uniform(epoch_jd=2460676.5, duration_s=2 * step_s, n=3)
        traj = propagate(coe, grid, method=PropagationMethod.TWO_BODY)
        angles = look_angles(
            traj, CASTELLDEFELS_LAT_RAD, CASTELLDEFELS_LON_RAD, CASTELLDEFELS_ALT_KM
        )
        finite_difference = (angles.range_km[0, 2] - angles.range_km[0, 0]) / (2 * step_s)
        # abs=1e-3 km/s, not 1e-6: a central difference has O(step_s^2) truncation
        # error, and at step_s=0.05 s on a curved range-vs-time trajectory the
        # residual measured here is ~4.4e-4 km/s — this bound catches a sign
        # error or a dropped term (which would be orders of magnitude larger),
        # not that truncation error.
        assert angles.range_rate_km_s[0, 1] == pytest.approx(finite_difference, abs=1e-3)


class TestPointAheadAngleZeroForRadialMotion:
    """A satellite moving straight along the line of sight needs no lead-ahead.

    Built directly in ITRF, where "radial" is exact: a point on the station's
    zenith radial, moving further along that same radial, so the transverse
    component the point-ahead angle depends on is exactly zero, not just small.
    """

    @pytest.mark.physics
    def test_pure_radial(self) -> None:
        zenith_direction = geodetic_to_itrf(CASTELLDEFELS_LAT_RAD, 0.0, 0.0)[0]
        zenith_direction = zenith_direction / np.linalg.norm(zenith_direction)
        r_itrf = zenith_direction * (WGS84_RADIUS_EQUATORIAL_KM + 700.0)
        v_itrf = zenith_direction * 1.0  # 1 km/s, straight up
        traj = _trajectory_from_itrf_state(r_itrf, v_itrf, epoch_jd=2451545.0)
        angles = look_angles(traj, CASTELLDEFELS_LAT_RAD, 0.0, 0.0)
        assert angles.point_ahead_angle_rad[0, 0] == pytest.approx(0.0, abs=1e-10)
        assert angles.range_rate_km_s[0, 0] == pytest.approx(1.0, abs=1e-10)


class TestPointAheadAngleFormula:
    """point_ahead_angle_rad matches ``2 * v_perp / c`` for a hand-built geometry.

    Satellite due east of an equatorial station, moving purely north —
    perpendicular to the station-to-satellite line of sight, which points
    along local east. Every metre per second of that velocity is transverse,
    so the point-ahead angle is exactly ``2 * speed / c`` with nothing to
    project out, and the range-rate is exactly zero.
    """

    @pytest.mark.physics
    def test_purely_transverse(self) -> None:
        station_r = geodetic_to_itrf(0.0, 0.0, 0.0)[0]
        offset_km = 500.0
        speed_km_s = 3.0
        r_itrf = station_r + np.array([0.0, offset_km, 0.0])  # +y is local east here
        v_itrf = np.array([0.0, 0.0, speed_km_s])  # +z is north
        traj = _trajectory_from_itrf_state(r_itrf, v_itrf, epoch_jd=2451545.0)
        angles = look_angles(traj, 0.0, 0.0, 0.0)
        expected = 2.0 * speed_km_s * 1000.0 / SPEED_OF_LIGHT_M_S
        assert angles.point_ahead_angle_rad[0, 0] == pytest.approx(expected, rel=1e-10)
        assert angles.range_rate_km_s[0, 0] == pytest.approx(0.0, abs=1e-9)


class TestPointAheadAngle:
    """The measured example the module docstring cites.

    Finds the highest-elevation sample over one pass of the 700 km SSO used
    throughout this repo — chosen, by a coarse day-long search recorded here
    rather than repeated in every test run, to bring the satellite to 67 deg
    over Castelldefels — and reports the point-ahead angle there. This is the
    test the module docstring's "Measured, not asserted" paragraph names — if
    the asserted values below ever need to change, that paragraph must be
    updated to match, never the other way around.

    The window searched is ``t_s`` in ``[21300, 21600)`` from the same epoch
    and elements as :func:`_sso_700km` with ``raan_rad=CASTELLDEFELS_LON_RAD``
    and ``true_anomaly_rad=275 deg``: a coarse scan of the whole sidereal day
    at 10 s resolution found the closest approach near ``t_s = 21441 s``, and
    this test resamples only that 300 s window at 0.1 s resolution rather than
    paying for day-long, sub-second sampling on every run.
    """

    @pytest.mark.physics
    def test_measured_example(self) -> None:
        coe = _sso_700km(raan_rad=CASTELLDEFELS_LON_RAD, true_anomaly_rad=np.deg2rad(275.0))
        grid = TimeGrid(epoch_jd=2460676.5, t_s=np.arange(21_300.0, 21_600.0, 0.1))
        traj = propagate(coe, grid, method=PropagationMethod.TWO_BODY)
        angles = look_angles(
            traj, CASTELLDEFELS_LAT_RAD, CASTELLDEFELS_LON_RAD, CASTELLDEFELS_ALT_KM
        )
        closest_idx = int(np.argmax(angles.elevation_rad[0]))
        max_elevation_deg = float(np.rad2deg(angles.elevation_rad[0, closest_idx]))
        paa_urad = float(angles.point_ahead_angle_rad[0, closest_idx]) * 1e6
        assert max_elevation_deg == pytest.approx(67.13, abs=0.05)
        assert paa_urad == pytest.approx(50.58, abs=0.05)


# --------------------------------------------------------------------------- #
# doppler_shift_hz
# --------------------------------------------------------------------------- #
class TestDopplerShift:
    @pytest.mark.physics
    def test_zero_range_rate_is_zero_shift(self) -> None:
        shift = doppler_shift_hz(np.array([0.0]), 1.934e14)
        assert shift[0] == pytest.approx(0.0, abs=0.0)

    @pytest.mark.physics
    def test_receding_is_redshift(self) -> None:
        shift = doppler_shift_hz(np.array([1.0]), 1.934e14)
        assert shift[0] < 0.0

    @pytest.mark.physics
    def test_approaching_is_blueshift(self) -> None:
        shift = doppler_shift_hz(np.array([-1.0]), 1.934e14)
        assert shift[0] > 0.0

    @pytest.mark.physics
    def test_linear_in_range_rate(self) -> None:
        shift_1 = doppler_shift_hz(np.array([1.0]), 1.934e14)
        shift_2 = doppler_shift_hz(np.array([2.0]), 1.934e14)
        assert shift_2[0] == pytest.approx(2.0 * shift_1[0], rel=1e-12)

    def test_rejects_bad_carrier(self) -> None:
        with pytest.raises(DomainError):
            doppler_shift_hz(np.array([1.0]), -1.0)
        with pytest.raises(DomainError):
            doppler_shift_hz(np.array([1.0]), float("nan"))

    def test_rejects_non_finite_range_rate(self) -> None:
        with pytest.raises(DomainError):
            doppler_shift_hz(np.array([float("nan")]), 1.934e14)


class TestDopplerRate:
    """How fast the shift sweeps: a different requirement from how far it moves.

    A coherent receiver has a **capture range** (how far off it can still find
    the carrier) and a **tracking rate** (how fast a loop can follow it once
    locked). A pass can sit inside the first and leave the second behind, and
    when it does the symptom is a lock that holds all pass and drops near the
    horizon — the shape of the TBIRD end-of-pass Doppler problem.
    """

    @pytest.mark.physics
    def test_a_constant_range_rate_is_not_sweeping(self) -> None:
        rate = doppler_rate_hz_s(np.full(7, 4.0), t_s=np.arange(7.0), carrier_frequency_hz=1.934e14)
        assert np.allclose(rate, 0.0, atol=0.0)

    @pytest.mark.physics
    def test_against_the_closed_form_on_a_quadratic_range(self) -> None:
        """V1 against the exact derivative, which a quadratic makes available.

        For ``R(t) = R0 + b t^2 / 2`` the range-rate is ``b t`` and the Doppler
        rate is exactly ``-f0 b / c``, a constant, so a second-order central
        difference of a linear range-rate is exact up to float rounding. That
        isolates the discretisation from the formula: if this fails, the factor
        or the sign is wrong, not the grid.
        """
        b = 0.37  # km/s^2
        t = np.linspace(0.0, 30.0, 61)
        rate = doppler_rate_hz_s(b * t, t_s=t, carrier_frequency_hz=1.934e14)
        exact = -1.934e14 * (b * 1e3) / SPEED_OF_LIGHT_M_S
        assert np.allclose(rate, exact, rtol=1e-12)

    @pytest.mark.physics
    def test_the_sign_is_the_shift_falling_and_not_the_range_growing(self) -> None:
        """The sign trips people up, so it is asserted against a physical picture.

        A satellite going from approaching to receding has a range-rate rising
        through zero and a Doppler shift falling through zero — blueshift to
        redshift. So a positive range acceleration is a **negative** Doppler
        rate, opposite to the intuition that "getting further, faster" should
        raise something.
        """
        t = np.arange(5.0)
        rate = doppler_rate_hz_s(np.arange(-2.0, 3.0), t_s=t, carrier_frequency_hz=1.934e14)
        shift = doppler_shift_hz(np.arange(-2.0, 3.0), 1.934e14)
        assert np.all(rate < 0.0)
        assert shift[0] > 0.0 > shift[-1]

    @pytest.mark.physics
    def test_it_is_the_derivative_of_the_shift_it_is_named_after(self) -> None:
        """Integrating the rate back over the window recovers the change in shift."""
        t = np.linspace(0.0, 120.0, 241)
        range_rate = 5.0 * np.cos(2.0 * np.pi * t / 400.0)
        shift = doppler_shift_hz(range_rate, 1.934e14)
        rate = doppler_rate_hz_s(range_rate, t_s=t, carrier_frequency_hz=1.934e14)
        recovered = float(np.trapezoid(rate, t))
        assert recovered == pytest.approx(float(shift[-1] - shift[0]), rel=1e-6)

    def test_it_differentiates_the_sample_axis_of_a_satellite_stack(self) -> None:
        """``LookAngles`` fields are ``(satellite, sample)``; the rate is per satellite."""
        t = np.arange(6.0)
        stack = np.vstack([t, 2.0 * t, -t])
        rate = doppler_rate_hz_s(stack, t_s=t, carrier_frequency_hz=1.934e14)
        assert rate.shape == stack.shape
        assert np.allclose(rate[1], 2.0 * rate[0], rtol=1e-12)
        assert np.allclose(rate[2], -rate[0], rtol=1e-12)

    def test_a_non_uniform_grid_is_handled_and_not_silently_assumed_uniform(self) -> None:
        """`TimeGrid` permits non-uniform spacing, so the derivative has to as well.

        Checked against the same linear range-rate sampled unevenly: a finite
        difference that divided by a single mean step would be wrong here and
        right on a uniform grid, which is how such a bug survives.
        """
        t = np.array([0.0, 0.5, 2.0, 5.0, 9.0, 14.0])
        rate = doppler_rate_hz_s(0.4 * t, t_s=t, carrier_frequency_hz=1.934e14)
        exact = -1.934e14 * (0.4 * 1e3) / SPEED_OF_LIGHT_M_S
        assert np.allclose(rate, exact, rtol=1e-10)

    @pytest.mark.parametrize(
        ("t_s", "match"),
        [
            (np.array([0.0]), "at least two samples"),
            (np.array([0.0, 0.0, 1.0]), "strictly increasing"),
            (np.array([0.0, 2.0, 1.0]), "strictly increasing"),
            (np.array([0.0, np.nan, 1.0]), "non-finite"),
            (np.zeros((2, 2)), "one-dimensional"),
        ],
    )
    def test_a_time_axis_that_is_not_one_is_refused(self, t_s: Any, match: str) -> None:
        with pytest.raises(DomainError, match=match):
            doppler_rate_hz_s(np.zeros(3), t_s=t_s, carrier_frequency_hz=1.934e14)

    def test_a_length_mismatch_is_refused_rather_than_broadcast(self) -> None:
        """Two axes that are meant to be the same axis, so a quiet broadcast is wrong."""
        with pytest.raises(DomainError, match="same time axis"):
            doppler_rate_hz_s(np.zeros(5), t_s=np.arange(4.0), carrier_frequency_hz=1.934e14)

    def test_a_bad_carrier_is_refused_by_the_shift_it_delegates_to(self) -> None:
        with pytest.raises(DomainError, match="carrier_frequency_hz"):
            doppler_rate_hz_s(np.zeros(3), t_s=np.arange(3.0), carrier_frequency_hz=0.0)


# --------------------------------------------------------------------------- #
# Input validation
# --------------------------------------------------------------------------- #
class TestRejectsBadInput:
    def test_non_teme_frame(self) -> None:
        # Frame.ITRF is not even a valid Trajectory frame (propagator.py
        # rejects a rotating frame at construction) — the frame that reaches
        # look_angles's own check is Frame.GCRF, declared on Frame but not
        # produced by anything in this package yet (see frames.py).
        grid = TimeGrid.uniform(epoch_jd=2460676.5, duration_s=1.0, n=2)
        traj = Trajectory(
            r_km=np.zeros((1, 2, 3)) + WGS84_RADIUS_EQUATORIAL_KM,
            v_km_s=np.zeros((1, 2, 3)),
            grid=grid,
            frame=Frame.GCRF,
            method=PropagationMethod.TWO_BODY,
        )
        with pytest.raises(DomainError, match="TEME"):
            look_angles(traj, 0.0, 0.0)

    def test_non_scalar_station(self) -> None:
        coe = _sso_700km(raan_rad=0.0, true_anomaly_rad=0.0)
        traj = _propagate_orbit(coe, span_s=100.0, n_samples=3)
        with pytest.raises(DomainError, match="scalar"):
            look_angles(traj, np.array([0.0, 0.1]), 0.0)

    def test_coincident_range_is_rejected(self) -> None:
        station_r = geodetic_to_itrf(CASTELLDEFELS_LAT_RAD, 0.0, 0.0)[0]
        traj = _trajectory_from_itrf_state(station_r, np.zeros(3), epoch_jd=2460676.5)
        with pytest.raises(DomainError, match="coincident"):
            look_angles(traj, CASTELLDEFELS_LAT_RAD, 0.0, 0.0)


# --------------------------------------------------------------------------- #
# LookAngles container
# --------------------------------------------------------------------------- #
class TestLookAnglesShapeChecks:
    def test_mismatched_shape_rejected(self) -> None:
        with pytest.raises(DomainError):
            LookAngles(
                elevation_rad=np.zeros((1, 2)),
                azimuth_rad=np.zeros((1, 3)),
                range_km=np.zeros((1, 2)),
                range_rate_km_s=np.zeros((1, 2)),
                point_ahead_angle_rad=np.zeros((1, 2)),
            )

    @pytest.mark.physics
    def test_multi_satellite_shape(self) -> None:
        coe = ClassicalElements.from_semi_major_axis(
            semi_major_axis_km=np.array([7078.137, 7178.137]),
            eccentricity=np.array([0.001, 0.001]),
            inclination_rad=np.deg2rad(98.19),
            raan_rad=0.0,
            argp_rad=0.0,
            true_anomaly_rad=0.0,
        )
        grid = TimeGrid.uniform(epoch_jd=2460676.5, duration_s=120.0, step_s=60.0)
        traj = propagate(coe, grid, method=PropagationMethod.TWO_BODY)
        angles = look_angles(
            traj, CASTELLDEFELS_LAT_RAD, CASTELLDEFELS_LON_RAD, CASTELLDEFELS_ALT_KM
        )
        assert angles.n_satellites == 2
        assert angles.n_samples == 3
        assert angles.elevation_rad.shape == (2, 3)
        assert repr(angles) == "LookAngles(n_satellites=2, n_samples=3)"


# --------------------------------------------------------------------------- #
# V3 — against astropy's AltAz frame
# --------------------------------------------------------------------------- #
@pytest.fixture(scope="module")
def reference() -> dict[str, Any]:
    """Return the frozen astropy AltAz reference data."""
    data: dict[str, Any] = json.loads(REFERENCE_PATH.read_text(encoding="utf-8"))
    return data


@pytest.mark.skipif(
    not REFERENCE_PATH.exists(),
    reason="geometry_reference.json not generated; see tests/golden/README.md",
)
@pytest.mark.physics
@pytest.mark.reference
class TestAgainstAstropyAltAz:
    """Elevation, azimuth and range against astropy's independent AltAz reduction.

    See ``tests/golden/generators/gen_geometry_reference.py`` for how the
    reference values were produced. Frozen, per ``tests/golden/README.md``:
    CI never regenerates this file, only reads it.
    """

    def test_reference_file_has_a_manifest(self, reference: dict[str, Any]) -> None:
        manifest = reference["manifest"]
        assert manifest["versions"]["astropy"]
        assert manifest["generator"].endswith("gen_geometry_reference.py")

    def test_elevation_azimuth_range_match_astropy(self, reference: dict[str, Any]) -> None:
        worst_elevation_deg = 0.0
        worst_azimuth_deg = 0.0
        worst_range_rel = 0.0
        for case in reference["look_angles"]:
            grid = TimeGrid.uniform(epoch_jd=case["jd_utc"], duration_s=1.0, n=2)
            r_teme = np.tile(np.array(case["r_teme_km"]), (2, 1))
            v_teme = np.tile(np.array(case["v_teme_km_s"]), (2, 1))
            traj = Trajectory(
                r_km=r_teme[np.newaxis, :, :],
                v_km_s=v_teme[np.newaxis, :, :],
                grid=grid,
                frame=Frame.TEME,
                method=PropagationMethod.TWO_BODY,
            )
            angles = look_angles(
                traj,
                np.deg2rad(case["station_latitude_deg"]),
                np.deg2rad(case["station_longitude_deg"]),
                case["station_altitude_km"],
            )
            el_deg = float(np.rad2deg(angles.elevation_rad[0, 0]))
            az_deg = float(np.rad2deg(angles.azimuth_rad[0, 0])) % 360.0
            range_km = float(angles.range_km[0, 0])

            worst_elevation_deg = max(
                worst_elevation_deg, abs(el_deg - case["elevation_astropy_deg"])
            )
            az_diff = (az_deg - case["azimuth_astropy_deg"] + 180.0) % 360.0 - 180.0
            worst_azimuth_deg = max(worst_azimuth_deg, abs(az_diff))
            worst_range_rel = max(
                worst_range_rel,
                abs(range_km - case["range_astropy_km"]) / case["range_astropy_km"],
            )

        # Bounds set from what this comparison actually measures, with margin
        # — not from the frame error budget alone, which sets the right order
        # of magnitude (quoss.orbits.frames' module docstring: ~14 m of
        # polar-motion residual and up to ~460 m from UT1~UTC at LEO range,
        # both well under a kilometre) but not the exact figure, because this
        # comparison also carries astropy's own AltAz refraction-model
        # bookkeeping and the two independent ellipsoid implementations. The
        # worst case measured across these 24 station x satellite x epoch
        # combinations: elevation and azimuth agree to a few thousandths of a
        # degree, range to 2.2e-4 relative (about 0.2-1.7 km depending on the
        # case's own range). All three are far below what a shape, sign, or
        # frame-mixing bug would produce (tens of degrees, or a wrong-sign
        # range).
        assert worst_elevation_deg < 0.05
        assert worst_azimuth_deg < 0.05
        assert worst_range_rel < 3e-4
