"""The committed `docs/validation.md` against a fresh run of the table.

Why the file is committed at all, when a command regenerates it
---------------------------------------------------------------
Because the two audiences are different, and only one of them can run
anything. `uv run python -m quoss.validation` serves the person with a
checkout; the committed file serves the person reading the repository on a web
page, the reviewer of a pull request, and — the case that decides it — the
reader who wants to know **what changed**. A generated file that is not
committed has no diff, so a refactor that moved the ITU-R P.1622 variance at
1.55 µm from 0.0659 to 0.0759 would change a status somewhere and leave no
trace in the history. With the file committed, that shows up as a line in the
diff of the same commit that caused it.

Why committing it needs this test
----------------------------------
Because a committed generated file is a *claim about the code*, and claims rot.
The moment the document says `reproduced` about a case the code now calls
`not reproduced`, it is worse than absent: it is the badge that
`docs/adr/0018-validation-is-a-table-not-a-badge.md` exists to prevent, printed
in Markdown with a table around it to look checked. The whole design of
`quoss.validation` — statuses derived and never typed, a case refusing to be
built with a status its own numbers do not give — would be undone by one stale
file in `docs/`.

So the comparison is **byte for byte** and not "close enough". The renderer was
built for it: no timestamps, no timings, four significant figures everywhere,
and sources ordered by first appearance rather than by a set. A render that
could not be compared exactly would push this test towards a fuzzy match, and a
fuzzy match on a document whose job is to carry exact numbers is not a check.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from quoss.validation.base import REGENERATE_COMMAND, render_markdown, run_all


@pytest.fixture(scope="module")
def committed(project_root: Path) -> str:
    """Return the text of `docs/validation.md` as it is in the tree."""
    path = project_root / "docs" / "validation.md"
    assert path.is_file(), (
        f"docs/validation.md is missing. It is a committed artefact; regenerate it with:\n"
        f"    {REGENERATE_COMMAND}"
    )
    return path.read_text(encoding="utf-8")


class TestTheCommittedDocumentIsTheGeneratedOne:
    def test_it_matches_byte_for_byte(self, committed: str) -> None:
        """The whole point of the file, and the failure message says how to fix it.

        If this fails, nothing is broken *yet*: the code moved and the document
        did not. The fix is one command, and the diff it produces is the
        interesting part — it says which published comparison this change moved,
        which is exactly the information a commit that changes physics should
        carry.
        """
        fresh = render_markdown(run_all())
        assert committed == fresh, (
            "docs/validation.md is out of date with the code. Regenerate it with:\n"
            f"    {REGENERATE_COMMAND}\n"
            "and read the diff: it names the published comparisons this change moved."
        )

    def test_the_header_names_the_command_that_writes_it(self, committed: str) -> None:
        """A generated file that names a command nobody can run is a worse instruction than none.

        Asserted against the constant rather than against a retyped string, so
        the header and the command cannot drift; that the command *exists* is
        `test_main.py`'s job, and that it lands here is this one's.
        """
        first_line = committed.splitlines()[0]
        assert first_line.startswith("<!-- Generated by")
        assert REGENERATE_COMMAND in first_line
        assert "tests/validation/test_docs.py" in first_line

    def test_every_disagreement_is_visible_in_the_document(self, committed: str) -> None:
        """A row that does not reproduce has to be readable as such, in the summary and in place.

        The label is bold Markdown (`**not reproduced**`) for one reason: a
        reader scanning a 35-row table should not have to compare the published
        and computed columns to notice one. Eight of them and the counter in the
        summary must agree, because the summary is what most readers will take
        away.
        """
        cases = run_all()
        disagreeing = [c for c in cases if c.status.value == "not_reproduced"]
        assert disagreeing, "the table has no disagreement; the summary line below would be wrong"
        assert f"| **not reproduced** | {len(disagreeing)} |" in committed
        for case in disagreeing:
            assert f"`{case.identifier}`" in committed

    def test_the_document_carries_no_v4(self, committed: str) -> None:
        """V2 and V3 only, asserted on the rendered text and not only on the objects.

        `ValidationCase` already refuses any other level, so this is the same
        guarantee read from the other end: whatever a future renderer does, the
        column a person actually reads may not say V4. A frozen snapshot of this
        project's own output is not validation (`tests/golden/README.md`), and
        the place that claim would leak in is a document, not a dataclass.
        """
        assert "| V4 |" not in committed
        assert "| V2 |" in committed
        assert "| V3 |" in committed
